name: test-and-publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Redis
      run: sudo apt-get install -y redis-server
    - name: Set up as module
      run: |
        HERE=`pwd`
        mkdir /tmp/project
        cd /tmp/project
        npm init -y
        npm install faker puppeteer@2.1.1 @userdashboard/dashboard @userdashboard/storage-cache-redis
        npm install -g mocha
        rm node_modules/@userdashboard/storage-cache-redis/*.js
        rm -rf node_modules/@userdashboard/storage-cache-redis/src
        cp $HERE/*.js node_modules/@userdashboard/storage-cache-redis
        cp -R $HERE/src/ node_modules/@userdashboard/storage-cache-redis/src/
        echo "global.applicationPath = __dirname" > main.js
    - name: Test unencrypted data caching with Redis
      run: |
        cd /tmp/project 
        mocha --file main.js --bail --exit --full-trace --recursive --timeout 90000000 "./node_modules/@userdashboard/**/{,!(public)}/*.test.js"
        cd $HERE
      env:
        NODE_ENV: "testing"
        FAST_START: "true"
        DASHBOARD_SERVER: http://localhost:9000
        DOMAIN: "localhost"
        CACHE: "@userdashboard/storage-cache-redis"
        CACHE_REDIS_URL: "redis://localhost:6379/15"
        GENERATE_SITEMAP_TXT: "false"
        GENERATE_API_TXT: "false"
    - name: Test encrypted data caching with Redis
      run: |
        cd /tmp/project 
        mocha --file main.js --bail --exit --full-trace --recursive --timeout 90000000 "./node_modules/@userdashboard/**/{,!(public)}/*.test.js"
        cd $HERE
      env:
        NODE_ENV: "testing"
        FAST_START: "true"
        DASHBOARD_SERVER: "http://localhost:9000"
        DOMAIN: "localhost"
        CACHE: "@userdashboard/storage-cache-redis"
        CACHE_REDIS_URL: "redis://localhost:6379/15"
        GENERATE_SITEMAP_TXT: "false"
        GENERATE_API_TXT: "false"
        ENCRYPTION_SECRET: "12345678901234567890123456789012"
        ENCRYPTION_SECRET_IV: "1234123412341234"
    - name: Increase NPM version
      run: |
        cd $HERE
        git config --global user.name "${{ secrets.NAME }}"
        git config --global user.email "${{ secrets.EMAIL }}"
        npm version patch
    - name: Publish to Github
      uses: stefanzweifel/git-auto-commit-action@v4.1.6
      with:
        commit_message: Automatically regenerated against current version
        branch: ${{ github.head_ref }}
        commit_options: '--no-verify --signoff'
        repository: .
    - name: Publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
